[package]
name = "demo-pac"
version = "0.1.0"
authors = ["James Munns <james.munns@ferrous-systems.com>"]
edition = "2018"

[dependencies]

[features]
alpha = []
beta = []
delta = []
gamma = []

default = []

all = ["alpha", "beta", "gamma", "delta"]
